# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 19:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classcast_search_fetch', '__first__'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classcast_karma_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('karma_points', models.FloatField()),
            ],
            options={
                'db_table': 'classcast_karma_history',
            },
        ),
        migrations.CreateModel(
            name='Classcast_student_info',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pincode', models.IntegerField()),
                ('standard', models.IntegerField()),
                ('stream', models.CharField(max_length=25)),
                ('marks_scored_in_last_degree', models.FloatField()),
                ('total_time_spent_on_platform', models.FloatField()),
                ('active_status', models.CharField(max_length=255)),
                ('last_active', models.DateTimeField()),
                ('total_karma_points', models.FloatField()),
                ('phone_number', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
            ],
            options={
                'db_table': 'classcast_student_info',
            },
        ),
        migrations.CreateModel(
            name='Classcast_test_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempts', models.IntegerField()),
                ('num_skips', models.IntegerField()),
                ('num_incorrect_attempts', models.IntegerField()),
                ('average_time_attempt', models.FloatField()),
                ('average_time_skip', models.FloatField()),
                ('curr_status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correctly_attempted_in_test', models.BooleanField()),
                ('correctly_attempted_in_gym', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classcast_search_fetch.question')),
            ],
            options={
                'db_table': 'classcast_test_submissions',
            },
        ),
        migrations.AddField(
            model_name='classcast_karma_history',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classcast_test_submission',
            unique_together=set([('student', 'xblock')]),
        ),
        migrations.AlterUniqueTogether(
            name='classcast_karma_history',
            unique_together=set([('student', 'date')]),
        ),
    ]
